version: "3.8"
services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey-local
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: [
      "valkey-server", "--save", "", "--appendonly", "no"
    ]
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5
